-- =====================================================================
-- Voluntiva — Migration 0002
-- Código inteiro público para ações sociais
--
-- MOTIVO
--   O protocolo VAP define `action_id` como inteiro positivo (docs/VAP.md
--   seção 4, e o teste test_strict_action_id rejeita explicitamente
--   strings). O schema usa UUID como chave primária.
--
--   Em vez de mudar o protocolo, damos à ação um segundo identificador:
--   `codigo`, inteiro, único e estável. A PK continua sendo o UUID —
--   toda FK do banco segue apontando para `id`.
--
--   Quem usa cada um:
--     API REST  -> UUID (id)      — identificador interno, não enumerável
--     VAP/TCP   -> inteiro (codigo) — curto, digitável num cliente CLI
--
--   TRADE-OFF a revisar: um código sequencial é enumerável. Alguém pode
--   varrer 1, 2, 3... e descobrir quantas ações existem. Para ação social
--   pública isso é irrelevante, mas registrem a escolha — se algum dia
--   houver ação privada, o `codigo` não pode ser o identificador dela.
--
--   ALTERNATIVA, se preferirem não ter dois identificadores: mudar o
--   protocolo para aceitar UUID em string. Isso exige editar
--   handlers.py (validação), docs/VAP.md (seção 4) e o parâmetro
--   test_strict_action_id, que hoje rejeita "1" por design.
-- =====================================================================

begin;

alter table public.acao_social
  add column if not exists codigo bigint generated by default as identity;

-- Preenche as linhas que já existiam antes desta migration.
update public.acao_social
   set codigo = sub.numero
  from (
    select id, row_number() over (order by criado_em, id) as numero
      from public.acao_social
     where codigo is null
  ) as sub
 where public.acao_social.id = sub.id
   and public.acao_social.codigo is null;

alter table public.acao_social
  alter column codigo set not null;

-- Realinha a sequência para o próximo valor livre, senão o primeiro
-- INSERT após o backfill colide com um código já usado.
select setval(
  pg_get_serial_sequence('public.acao_social', 'codigo'),
  coalesce((select max(codigo) from public.acao_social), 0) + 1,
  false
);

alter table public.acao_social
  add constraint acao_codigo_uk unique (codigo);

comment on column public.acao_social.codigo is
  'Identificador público inteiro, usado como action_id no protocolo VAP. A chave primária continua sendo id (uuid).';

-- A view precisa expor o código, senão LIST_ACTIONS não tem o que devolver.
drop view if exists public.vw_acao_vagas;

create view public.vw_acao_vagas
  with (security_invoker = true)
as
select
  a.id                as acao_id,
  a.codigo,
  a.ong_id,
  o.nome              as ong_nome,
  a.unidade_id,
  a.titulo,
  a.inicio,
  a.fim,
  a.status,
  a.vagas,
  count(i.id) filter (where i.status = 'confirmada')  as vagas_ocupadas,
  a.vagas - count(i.id) filter (where i.status = 'confirmada') as vagas_disponiveis,
  count(i.id) filter (where i.status = 'lista_espera') as em_lista_espera
from public.acao_social a
join public.ong o on o.id = a.ong_id
left join public.inscricao i on i.acao_id = a.id
group by a.id, o.nome;

comment on view public.vw_acao_vagas is
  'Ocupação por ação social. Base para LIST_EVENTS (REST) e LIST_ACTIONS (VAP).';

commit;
