"""Catálogo de habilidades e ações sociais (eventos)."""
from __future__ import annotations

import datetime as dt
import uuid

from sqlalchemy import BigInteger, DateTime, FetchedValue, ForeignKey, Integer, String, Text, Uuid, func
from sqlalchemy.dialects.postgresql import ENUM as PGEnum
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base
from app.models.enums import StatusAcao

_status_acao = PGEnum(
    StatusAcao, name="status_acao", create_type=False,
    values_callable=lambda e: [m.value for m in e],
)


class Habilidade(Base):
    __tablename__ = "habilidade"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, server_default=func.gen_random_uuid())
    nome: Mapped[str] = mapped_column(String(80), nullable=False)
    categoria: Mapped[str | None] = mapped_column(String(80))
    descricao: Mapped[str | None] = mapped_column(Text)
    criado_em: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    def __repr__(self) -> str:
        return f"<Habilidade {self.nome}>"


class AcaoSocial(Base):
    __tablename__ = "acao_social"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, server_default=func.gen_random_uuid())
    # Identificador público inteiro, usado como action_id no protocolo VAP.
    # GENERATED BY DEFAULT AS IDENTITY: o banco atribui, nunca atribua em Python.
    codigo: Mapped[int] = mapped_column(BigInteger, server_default=FetchedValue())
    ong_id: Mapped[uuid.UUID] = mapped_column(Uuid, ForeignKey("ong.id", ondelete="RESTRICT"), nullable=False)
    unidade_id: Mapped[uuid.UUID | None] = mapped_column(Uuid, ForeignKey("unidade.id", ondelete="SET NULL"))
    titulo: Mapped[str] = mapped_column(String(160), nullable=False)
    descricao: Mapped[str | None] = mapped_column(Text)
    local_texto: Mapped[str | None] = mapped_column(Text)
    inicio: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    fim: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    vagas: Mapped[int] = mapped_column(Integer, nullable=False)
    status: Mapped[StatusAcao] = mapped_column(_status_acao, nullable=False, server_default="rascunho")
    criado_por: Mapped[uuid.UUID | None] = mapped_column(Uuid, ForeignKey("usuario.id", ondelete="SET NULL"))
    criado_em: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    atualizado_em: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    habilidades: Mapped[list[AcaoHabilidade]] = relationship(
        back_populates="acao", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<AcaoSocial {self.titulo} ({self.status})>"


class AcaoHabilidade(Base):
    __tablename__ = "acao_habilidade"

    acao_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("acao_social.id", ondelete="CASCADE"), primary_key=True
    )
    habilidade_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("habilidade.id", ondelete="RESTRICT"), primary_key=True
    )
    obrigatoria: Mapped[bool] = mapped_column(nullable=False, server_default="false")

    acao: Mapped[AcaoSocial] = relationship(back_populates="habilidades")
    habilidade: Mapped[Habilidade] = relationship()
